version: "3.8"

services:
  # Maria DB
  db:
    container_name: weather-wise-db
    image: mariadb:latest
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data-storing/export/:/docker-entrypoint-initdb.d # Load the seeded data when the container is created
      - ./db_data:/var/lib/mysql # Persist the data
    ports:
      - "3307:3306" # 3307 (host) to 3306 (container). 3306 is (maybe) used by local MySQLis already used by host's local MySQL
    networks:
      - weather-wise-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-P",
          "3307",
          "-u",
          "root",
          "-p$$MYSQL_PASSWORD",
        ]
      interval: 60s
      timeout: 5s
      retries: 5

  # App development
  app-dev:
    container_name: weather-wise-dev
    build:
      context: .
      target: app_dev
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./data-visualization:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    networks:
      - weather-wise-network

  # App production
  app-prod:
    container_name: weather-wise-prod
    build:
      context: .
      target: app_runner
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - weather-wise-network

  # Scheduler
  scheduler:
    container_name: weather-wise-scheduler
    build:
      context: .
      target: scheduler_runner
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - weather-wise-network

volumes:
  db_data:

networks: # Network for the services
  weather-wise-network:
    external: true
    driver: bridge
