version: '3.8'
services:
  mariadb:
    image: mariadb:lts-ubi9
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: basdat
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      # - ./Data Storing/export/basdat.sql:/docker-entrypoint-initdb.d/basdat.sql
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:
